### ISSUE TITLE
[alexnuttinck/helm-7dtd] issue title

### ISSUE THREAD

**Issue by veenarm** [alexnuttinck/helm-7dtd#3]
There is a typo in the referece to the `7dtd-http`  service

The name  has `htto` instead of `http` - causing the service to not route traffic to the application POD got port `8082`

- service.yaml
```yaml
    - name: 7dtd-http
      port: 8082
      protocol: TCP
      targetPort: 7dtd-http
```

deployment.yaml
```yaml
          - name: 7dtd-htto
            containerPort: 8082
            protocol: TCP
```

P.S - Also not having any PV/PVCS configured is a detriment as it's a 16GB download every time the application server restarts.
